image: "buildah/buildah"

compile:
  stage: build
  variables:
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
  before_script:
    - podman login -u $CI_USER -p $CI_TOKEN $CI_REGISTRY
  script:
    - export CI_DATE=$(date +%F)
    - podman build -t $CI_REGISTRY/$CI_IMAGE:$CI_DATE -t $CI_REGISTRY/$CI_IMAGE:latest -f Containerfile .
    - podman push -q $CI_REGISTRY/$CI_IMAGE:$CI_DATE
    - podman push -q $CI_REGISTRY/$CI_IMAGE:latest
  after_script:
    - podman logout $CI_REGISTRY
