[bumpver]
current_version = "22.5.1-alpha"
version_pattern = "YY.MM.PATCH[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"README.md" = [
    "{version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"main.go" = [
    '"version": "{version}",'
]
".gitlab-ci.yml" = [
    'VERSION: "{version}"',
]