// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"georgslauf/internal/db"
	"georgslauf/internal/settings"
	"georgslauf/md"
	"georgslauf/session"
	"strconv"
)

func HostStationCategory(category db.GetStationCategoriesRow) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"flex gap-x-3 items-end\" hx-put=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("/host/stations/categories/" + strconv.FormatInt(category.ID, 10))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 14, Col: 76}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-swap=\"outerHTML\" hx-target=\"this\"><label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Name</span></div><input autocomplete=\"off\" required maxlength=\"30\" minlength=\"3\" name=\"name\" type=\"text\" placeholder=\"Name\" class=\"invalid:border-error input input-bordered w-full max-w-xs\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(category.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 31, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></label> <label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Max. Anzahl (angemeldet: <strong>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(category.Count, 10))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 36, Col: 101}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</strong>)</span></div><input autocomplete=\"off\" name=\"max\" min=\"0\" type=\"number\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(category.Max, 10))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 38, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" required placeholder=\"Anzahl\" class=\"invalid:border-error input input-bordered w-full max-w-xs\"></label> <button class=\"btn btn-primary\"><span class=\"text-lg icon-[mdi--content-save]\"></span></button><form hx-disinherit=\"*\"><button hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs("/host/stations/categories/" + strconv.FormatInt(category.ID, 10))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 47, Col: 81}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"btn btn-error\"><span class=\"text-xl icon-[mdi--delete]\"></span></button></form></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func HostStationCategoryNew() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<form class=\"flex gap-x-3 items-end\" hx-post=\"/host/stations/categories\" hx-swap=\"outerHTML\" hx-target=\"this\"><label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Name</span></div><input autocomplete=\"off\" required maxlength=\"30\" minlength=\"3\" name=\"name\" type=\"text\" placeholder=\"Name\" class=\"invalid:border-error input input-bordered w-full max-w-xs\" value=\"\"></label> <label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Max. Anzahl</span></div><input autocomplete=\"off\" name=\"max\" min=\"0\" type=\"number\" value=\"0\" required placeholder=\"Anzahl\" class=\"invalid:border-error input input-bordered w-full max-w-xs\"></label> <button class=\"btn btn-primary\"><span class=\"text-lg icon-[mdi--content-save]\"></span></button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func HostSettings(htmxRequest bool, user *session.UserData, set *settings.Settings, schedule []db.Schedule, categories []db.GetStationCategoriesRow, home md.MdData, positions []db.GetStationPositionsStationRow) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var9 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"mt-6 mx-auto px-3 max-w-screen-xl\"><div role=\"tablist\" class=\"tabs tabs-bordered\" hx-swap=\"innerHTML\" hx-target=\"main\" hx-push-url=\"true\"><a role=\"tab\" class=\"tab\" hx-get=\"/host/tribes\">Übersicht</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/groups\">Gruppen</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/stations\">Posten</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/users\">Accounts</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/points\">Bewertungen</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/stats\">Statistik</a> <a role=\"tab\" class=\"tab\" hx-get=\"/host/results/stations\">Auswertung</a> <a role=\"tab\" class=\"tab tab-active\" hx-get=\"/host/settings\">Einstellungen</a></div><div class=\"mt-6 space-y-6\"><details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Gruppen</summary><div class=\"collapse-content\"><form hx-put=\"/host/settings/groups\" hx-trigger=\"change\" hx-swap=\"none\" class=\"space-y-3\"><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><div class=\"label-text\">Gruppen erstellen<div class=\"tooltip\" data-tip=\"StaVos können Gruppen anlegen\"><span class=\"ml-2 w-6 h-6 align-bottom icon-[mdi--information-slab-symbol]\"></span></div></div><input name=\"group-create\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Groups.AllowCreate {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Gruppen verändern<div class=\"tooltip\" data-tip=\"StaVos können ihre Gruppen verändern\"><span class=\"ml-2 w-6 h-6 align-bottom icon-[mdi--information-slab-symbol]\"></span></div></span> <input name=\"group-update\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Groups.AllowUpdate {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Gruppen löschen<div class=\"tooltip\" data-tip=\"StaVos können ihre Gruppen löschen\"><span class=\"ml-2 w-6 h-6 align-bottom icon-[mdi--information-slab-symbol]\"></span></div></span> <input name=\"group-delete\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Groups.AllowDelete {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Laufgruppe anzeigen<div class=\"tooltip\" data-tip='z.B. \"Laufgruppe 2\" den Posten und StaVos anzeigen'><span class=\"ml-2 w-6 h-6 align-bottom icon-[mdi--information-slab-symbol]\"></span></div></span> <input name=\"group-abbr\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Groups.ShowAbbr {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "></label></div><label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Größe Minimum</span></div><input autocomplete=\"off\" name=\"group-min\" min=\"0\" type=\"number\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(set.Groups.Min, 10))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 195, Col: 118}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "\" required placeholder=\"Type here\" class=\"invalid:border-error input input-bordered w-full max-w-xs\"></label> <label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Größe Maximum (muss größer als min. sein)</span></div><input autocomplete=\"off\" name=\"group-max\" min=\"0\" type=\"number\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.FormatInt(set.Groups.Max, 10))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 201, Col: 118}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" required placeholder=\"Type here\" class=\"invalid:border-error input input-bordered w-full max-w-xs\"></label></form></div></details> <details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Posten</summary><div class=\"collapse-content\"><form hx-put=\"/host/settings/stations\" hx-trigger=\"change\" hx-swap=\"none\" class=\"space-y-3\"><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten erstellen</span> <input name=\"station-create\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.AllowCreate {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten verändern</span> <input name=\"station-update\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.AllowUpdate {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten löschen</span> <input name=\"station-delete\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.AllowDelete {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten Kategorien verwenden</span> <input name=\"station-categories\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.EnableCategories {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten Standort anzeigen</span> <input name=\"station-abbr\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.ShowAbbr {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Bewertungen freischalten</span> <input name=\"station-scoring\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.AllowScoring {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">StaVos können Accounts an Posten verändern</span> <input name=\"station-accounts\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.EditAccounts {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "></label></div><div class=\"form-control max-w-xs\"><label class=\"label cursor-pointer\"><span class=\"label-text\">Posten können Accounts an ihren Posten verändern</span> <input name=\"station-accounts-self\" type=\"checkbox\" class=\"toggle\" value=\"true\" autocomplete=\"off\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if set.Stations.EditAccountsStation {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, " checked=\"checked\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "></label></div></form></div></details> <details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Posten Kategorien</summary><div class=\"collapse-content\"><p class=\"mb-3 font-light\">Max. Anzahl 0 = kein Limit</p><div id=\"category-list\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, category := range categories {
				templ_7745c5c3_Err = HostStationCategory(category).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</div><button hx-get=\"/host/stations/categories/new\" hx-swap=\"beforeend\" hx-target=\"#category-list\" class=\"mt-3 btn btn-secondary\">Hinzufügen</button></div></details> <details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Posten Standorte</summary><div class=\"collapse-content\"><ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, position := range positions {
				if position.StationName.Valid {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "<li><strong>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var12 string
					templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(position.PositionName)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 363, Col: 44}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</strong> ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var13 string
					templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(position.StationName.String)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 363, Col: 85}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</li>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "<li><strong>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var14 string
					templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(position.PositionName)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 365, Col: 44}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "</strong> <span class=\"font-light\">kein Posten</span></li>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "</ul></div></details><details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Startseite</summary><div class=\"collapse-content\"><form hx-put=\"/host/settings/home\" hx-trigger=\"change\" hx-swap=\"innerHTML\" hx-target=\"next article\" class=\"space-y-3\"><label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Titel</span></div><input autocomplete=\"off\" maxlength=\"64\" name=\"headline\" type=\"text\" placeholder=\"Georgslauf\" class=\"input input-bordered w-full\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(set.Home.Headline)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 396, Col: 163}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "\"></label> <label class=\"form-control\"><div class=\"label\"><span class=\"label-text\">Startseite (markdown)</span></div><textarea autocomplete=\"off\" maxlength=\"2048\" name=\"intro\" class=\"textarea textarea-bordered h-96\" placeholder=\"\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(set.Home.Intro)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 402, Col: 138}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "</textarea></label></form><div class=\"mt-4\"><p class=\"mb-3\">Vorschau</p><article class=\"prose bg-base-300 p-4 rounded-md max-w-full text-wrap\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(string(home.Intro)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "</article></div></div></details> <details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Anmeldung</summary><div class=\"collapse-content\"><form hx-put=\"/host/settings/login\" hx-trigger=\"change\" hx-swap=\"none\" class=\"space-y-3\"><label class=\"form-control w-full max-w-xs\"><div class=\"label\"><span class=\"label-text\">Titel nach Anmeldung</span></div><input autocomplete=\"off\" maxlength=\"64\" name=\"title\" type=\"text\" placeholder=\"Georgslauf\" class=\"input input-bordered w-full max-w-xs\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var17 string
			templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(set.Login.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 426, Col: 167}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "\"></label> <label class=\"form-control\"><div class=\"label\"><span class=\"label-text\">Nachricht nach Anmeldung</span></div><textarea autocomplete=\"off\" maxlength=\"1024\" name=\"welcome\" class=\"textarea textarea-bordered h-24\" placeholder=\"Nachricht\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var18 string
			templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(set.Login.Welcome)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 432, Col: 152}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</textarea></label></form></div></details> <details class=\"collapse bg-base-200\" open><summary class=\"collapse-title text-xl font-medium\">Hilfe</summary><div class=\"collapse-content\"><form hx-put=\"/host/settings/help\" hx-trigger=\"change\" hx-swap=\"none\" class=\"space-y-3\"><label class=\"form-control w-full\"><div class=\"label\"><span class=\"label-text\">Hilfe Link im Footer</span></div><input autocomplete=\"off\" maxlength=\"128\" name=\"footer\" type=\"text\" placeholder=\"https://...\" class=\"input input-bordered w-full\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var19 string
			templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(set.Help.Footer)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `host_settings.templ`, Line: 450, Col: 161}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "\"></label></form></div></details></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = base(htmxRequest, user, -1, false).Render(templ.WithChildren(ctx, templ_7745c5c3_Var9), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
