server:
  host: "0.0.0.0"
  port: "8080"
  metrics:
    username: "prometheus"
    password: "CHANGE_ME"
database:
  replication: false
  path: "data.db"
  remote: "http://127.0.0.1:8954"
  # encryption: "CHANGE_ME"
  # token: "base64_encoded_CHANGE_ME"
auth:
  domain: "id.georgslauf.de"
  clientID: "CHANGE_ME"
  key: "CHANGE_ME"
  callback: "https://georgslauf.de/auth/callback"
