server:
  host: "0.0.0.0"
  port: "8080"
  metrics:
    username: "prometheus"
    password: "Shock-Playable-Drippy1-Caboose-Slideshow-Hardcopy-Gratuity-Twitter-Slicing-Deceiving"
database:
  path: "file:///home/exampleUser/georgslauf/data.db"
