// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"georgslauf/acl"
)

type Group struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	UpdatedAt int64
	UpdatedBy sql.NullInt64
	Name      string
	Abbr      sql.NullString
	Size      sql.NullInt64
	Comment   sql.NullString
	Grouping  int64
	TribeID   int64
	ImageID   sql.NullString
	Vegan     int64
}

type GroupRole struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	UpdatedAt int64
	UpdatedBy sql.NullInt64
	UserID    int64
	GroupID   int64
	GroupRole acl.ACL
}

type Image struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	Filepath  string
	TribeID   sql.NullInt64
	StationID sql.NullInt64
}

type PointsToGroup struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	UpdatedAt int64
	UpdatedBy sql.NullInt64
	StationID int64
	GroupID   int64
	Points    int64
}

type PointsToStation struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	UpdatedAt int64
	UpdatedBy sql.NullInt64
	GroupID   int64
	StationID int64
	Points    int64
}

type Schedule struct {
	ID    int64
	Start int64
	End   sql.NullInt64
	Name  string
}

type Setting struct {
	ID        int64
	UpdatedAt int64
	UpdatedBy sql.NullInt64
	Data      []byte
}

type Station struct {
	ID           int64
	CreatedAt    int64
	CreatedBy    sql.NullInt64
	UpdatedAt    int64
	UpdatedBy    sql.NullInt64
	Name         string
	PositionID   sql.NullInt64
	Size         int64
	Vegan        int64
	TribeID      int64
	CategoryID   sql.NullInt64
	ImageID      sql.NullString
	Description  sql.NullString
	Requirements sql.NullString
}

type StationCategory struct {
	ID   int64
	Name string
	Max  int64
}

type StationPosition struct {
	ID   int64
	Name string
}

type StationRole struct {
	ID          int64
	CreatedAt   int64
	CreatedBy   sql.NullInt64
	UpdatedAt   int64
	UpdatedBy   sql.NullInt64
	UserID      int64
	StationID   int64
	StationRole acl.ACL
}

type Tribe struct {
	ID          int64
	CreatedAt   int64
	UpdatedAt   int64
	Name        string
	Short       sql.NullString
	Dpsg        sql.NullString
	ImageID     sql.NullString
	EmailDomain sql.NullString
	StavoEmail  sql.NullString
}

type TribeIcon struct {
	ID        int64
	CreatedAt int64
	CreatedBy sql.NullInt64
	Image     []byte
}

type TribeRole struct {
	ID         int64
	CreatedAt  int64
	CreatedBy  sql.NullInt64
	UpdatedAt  int64
	UpdatedBy  sql.NullInt64
	UserID     int64
	TribeID    int64
	TribeRole  acl.ACL
	AcceptedAt sql.NullInt64
}

type User struct {
	ID        int64
	ExtID     sql.NullString
	Username  string
	Email     string
	LastLogin int64
	CreatedAt int64
	Role      acl.ACL
	Firstname string
	Lastname  string
}

type UserIcon struct {
	ID        int64
	CreatedAt int64
	Image     []byte
}
